pipeline {
    agent any

    stages { 
        stage('Install Docker') {
            steps {
                script {
                    echo 'Installing Docker'
                    sh '''
                    sudo yum update -y
                    sudo yum install -y docker
                    sudo service docker start
                    sudo usermod -a -G docker ec2-user
                    newgrp docker
                    '''
                }
            }
        }

        stage('Run Nginx with Custom Index.html') {
            steps {
                script {
                    echo 'Running Nginx with a custom index.html'
                    sh '''
                    docker run -d -p 8080:80 --name web -v $WORKSPACE/index.html:/usr/share/nginx/html/index.html nginx
                    '''
                }
            }
      
        stage('Test if its works') {
              steps {
                script {
                    echo 'Testing the deployment'
                    sh 'sudo curl http://localhost:8080'
                    }
                }
            }
        }
}
