pipeline {
    agent any

    stages {
        stage('Install Apache') {
            steps {
                script {
                    echo 'Installing Apache'
                    sh 'sudo dnf update -y'
                    sh 'sudo dnf list | grep httpd'
                    sh 'sudo dnf install -y httpd.x86_64'
                    sh 'sudo systemctl start httpd.service'
                    sh 'sudo systemctl enable httpd.service'
                        }
                    }
                }

            stage('Test if its works') {
                steps {
                    script {
                        echo 'Test if its works'
                        sh 'sudo curl http://localhost/'
                        }
                    }
                }
        }
}
